services:
  test:
    shm_size: '12gb'
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    ipc: host
    environment:
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1
    security_opt:
      - seccomp=unconfined
    cap_add:
      - NET_ADMIN
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:$HOME/.Xauthority:rw
      - ./test_ws:/home/test_ws
    privileged: true
    stdin_open: true
    tty: true
    command: /bin/bash
